### ISSUE TITLE
Relative path for image support

### ISSUE THREAD

**Issue by Mylloon** [xy2z/PineDocs#170]
Find images correctly with a relative path to render the image correctly in markdown.

Example:
```
                ┌────────────────────────────┐
                │                            │
                │   # Here an image          │
                │   ![Image](Folder1/pic.png)│
                │                            │
Root            └────────┬───────────────────┘
  │                      │
  │                      │
  │                      │
  ├───file.md ◄──────────┘
  │
  │
  └───Folder1
      │
      │
      └─────pic.png
```

**Comment by xy2z** [comment]
I think this should be possible in index.php by checking if referer is the same as the host, and if it is then get the file from the `content` dir instead of `public` dir, that is the best solution i can think of, but it pobably needs some fiddling and testing.

This way it would work for images, audio, video, etc.

But im not sure if browsers can disable the referer? Even if it's the same host.
